global:
  scrape_interval:     5s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'performance-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cAdvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:9091']

  - job_name: 'batch-job'
    scrape_interval: 5s
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['job:8080']

  - job_name: 'consumer-app'
    scrape_interval: 5s
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'app:8080' ]